Improvements
milan44i/calendar pull request #2
Opened 2024-06-05 09:30 UTC by milan44i

2024-06-10 11:07 UTC, Saraaaaaaaaaaaaaaa requested changes

2024-06-10 11:07 UTC, Saraaaaaaaaaaaaaaa commented on src/components/functions.ts
> +export const isCurrentMonth = (date: Date) => isThisMonth(date);
You can also use date-fns func here:

`export const isCurrentMonth = (date: Date) => isThisMonth(date)`

2024-06-10 11:07 UTC, Saraaaaaaaaaaaaaaa commented on src/components/functions.ts
> +export const areDatesEqual = (date1: Date, date2: Date) =>
Use `isSameDay`:

`export const areDatesEqual = (date1: Date, date2: Date) => isSameDay(date1, date2)`

2024-06-10 11:07 UTC, Saraaaaaaaaaaaaaaa commented on src/components/functions.ts
> +  const time = navigator.language === "sr" ? "17:00" : "5:00 PM";
The times are currently hard-coded, which limits flexibility. To make the function more versatile, consider passing the time as a parameter instead of using fixed values.

2024-06-10 12:17 UTC, milan44i commented on src/components/functions.ts
> +  const time = navigator.language === "sr" ? "17:00" : "5:00 PM";
Right now we don't have support for time picking, so I left this hardcoded until we implement that.

2024-06-10 14:08 UTC, anyamiletic reviewed
<img width="373" alt="Screenshot 2024-06-10 at 15 37 31" src="https://github.com/milan44i/calendar/assets/31810954/22d16b30-d127-4663-a917-804dafd66948">

we should probably show the current selected month's days in white

2024-06-10 14:08 UTC, anyamiletic commented on src/components/EventCalendar.tsx
> +                        <time
let's move the entire meeting to a separate component

2024-06-10 14:08 UTC, anyamiletic commented on src/components/functions.ts
> +export const getLocale = (locale: string) => {
```suggestion
export const getLocale = (locale: string): Locale => {
```

2024-06-10 14:08 UTC, anyamiletic commented on src/components/types.ts
> +  datetime: string | Date; // will be Date only
why do we have all 3 fields? We should have a single date that has all information. Usually the best practice is for that obj to be saved as a UTC time, then we can show different representations based on locale and timezones

2024-06-10 14:08 UTC, anyamiletic commented on src/components/functions.ts
> +    id: 0,
randomize id so that multiple events can be added and displayed using `key={id}`

2024-06-10 15:28 UTC, milan44i commented on src/components/Calendar.tsx
this now returns weekdays dynamically, but getLocale function still only returns 2 locales - srLatn and enUS, we might want to make that more dynamic as well

2024-06-10 15:37 UTC, milan44i commented on src/components/functions.ts
> +export const getLocale = (locale: string) => {
No need, type inference does its job, at least in my editor :D

2024-06-10 15:41 UTC, milan44i commented on src/components/functions.ts
> +    id: 0,
id is calculated in handleAddEvent function based on the lenght of the array, so it will always be different. I put id: 0 here just so the return type can be 'Event'. The other thing I can do here is make return type of this function omit 'id' property from Event type. Let me know what you think about that solution

2024-06-10 16:31 UTC, milan44i commented on src/components/Calendar.tsx
>  type CalendarProps = {
I left only selectedDay and handleSelectedDay as mandatory props

2024-06-11 07:24 UTC, anyamiletic commented on src/components/functions.ts
> +export const getLocale = (locale: string) => {
we should be consistent, we either always put return types or never. IMO putting return types has several benefits
- no need to hover on the function and rely on the editor to infer the type
- everything is in one line and easy to read 
- you can click-through the return type to go to its definition
Hope i've convinced you :)

2024-06-11 07:26 UTC, anyamiletic commented on src/components/functions.ts
> +    id: 0,
no need, just put a comment saying the id will be changed afterwards

2024-06-11 09:19 UTC, anyamiletic commented on src/components/Calendar.tsx
> +  const monthNumber = selectedMonthYear.getMonth(); // 0-11
we don't need this, `selectedMonthYear` can be used for `start` and `end` dates

2024-06-11 09:19 UTC, anyamiletic commented on src/components/Calendar.tsx
> +                dateTime={formattedDate}
if we use `date.toString()` here and use `format(date, 'd')` below, we don't need the `formattedDate` constant

2024-06-11 09:19 UTC, anyamiletic commented on src/components/Calendar.tsx
> +                  isSameDay(selectedDay, date) && "bg-gray-900",
all functions are being used more than once so we can move them up

2024-06-11 13:07 UTC, anyamiletic approved these changes

2024-06-11 14:44 UTC, merged